import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:secret_vault_app/app.dart';
import 'package:secret_vault_app/core/constants/app_constants.dart';
import 'package:secret_vault_app/features/favorites/data/models/favorite_item_model.dart';
import 'package:secret_vault_app/features/history/data/models/watch_history_model.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Show status bar and navigation bar (opt out of full edge-to-edge).
  // This prevents the AppBar from being obscured by the transparent status bar
  // that Flutter/Material3 enables by default on Android.
  await SystemChrome.setEnabledSystemUIMode(
    SystemUiMode.manual,
    overlays: SystemUiOverlay.values, // show both status bar AND nav bar
  );

  // Set global overlay style: dark background → light (white) status bar icons.
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.light,
    statusBarBrightness: Brightness.dark,
  ));

  // Lock to portrait for the main app (player page unlocks landscape separately).
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  // Initialize Hive for local favorites storage
  await Hive.initFlutter();

  // Register the FavoriteItemModel adapter (generated by hive_generator)
  if (!Hive.isAdapterRegistered(FavoriteItemModelAdapter().typeId)) {
    Hive.registerAdapter(FavoriteItemModelAdapter());
  }

  // Register the WatchHistoryModel adapter (typeId = 1)
  if (!Hive.isAdapterRegistered(WatchHistoryModelAdapter().typeId)) {
    Hive.registerAdapter(WatchHistoryModelAdapter());
  }

  // Open the favorites box before running the app
  await Hive.openBox<FavoriteItemModel>(AppConstants.favoritesBoxName);

  // Open the watch-history box
  await Hive.openBox<WatchHistoryModel>(AppConstants.watchHistoryBoxName);

  runApp(
    // ProviderScope wraps the entire app so Riverpod providers are accessible everywhere
    const ProviderScope(
      child: App(),
    ),
  );
}
